
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Button btnConetar;
	
	private global::Gtk.ComboBox combobox4;
	
	private global::Gtk.Button btnDesconectar;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button btnLED1;
	
	private global::Gtk.Button btnLED2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView visualizador;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Controlador de LEDs");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnConetar = new global::Gtk.Button ();
		this.btnConetar.CanFocus = true;
		this.btnConetar.Name = "btnConetar";
		this.btnConetar.UseUnderline = true;
		this.btnConetar.Label = global::Mono.Unix.Catalog.GetString ("Conectar");
		this.hbox3.Add (this.btnConetar);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnConetar]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.combobox4 = global::Gtk.ComboBox.NewText ();
		this.combobox4.Name = "combobox4";
		this.hbox3.Add (this.combobox4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.combobox4]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnDesconectar = new global::Gtk.Button ();
		this.btnDesconectar.CanFocus = true;
		this.btnDesconectar.Name = "btnDesconectar";
		this.btnDesconectar.UseUnderline = true;
		this.btnDesconectar.Label = global::Mono.Unix.Catalog.GetString ("Desconectar");
		this.hbox3.Add (this.btnDesconectar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnDesconectar]));
		w3.Position = 2;
		w3.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnLED1 = new global::Gtk.Button ();
		this.btnLED1.CanFocus = true;
		this.btnLED1.Name = "btnLED1";
		this.btnLED1.UseUnderline = true;
		this.btnLED1.Label = global::Mono.Unix.Catalog.GetString ("LED A");
		this.hbox2.Add (this.btnLED1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnLED1]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnLED2 = new global::Gtk.Button ();
		this.btnLED2.CanFocus = true;
		this.btnLED2.Name = "btnLED2";
		this.btnLED2.UseUnderline = true;
		this.btnLED2.Label = global::Mono.Unix.Catalog.GetString ("LED B");
		this.hbox2.Add (this.btnLED2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnLED2]));
		w6.Position = 1;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.visualizador = new global::Gtk.TextView ();
		this.visualizador.CanFocus = true;
		this.visualizador.Name = "visualizador";
		this.visualizador.Editable = false;
		this.GtkScrolledWindow.Add (this.visualizador);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w9.Position = 2;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 410;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnConetar.Clicked += new global::System.EventHandler (this.btnConectar_Clicked);
		this.btnDesconectar.Clicked += new global::System.EventHandler (this.btnDesconectar_Clicked);
		this.btnLED1.Clicked += new global::System.EventHandler (this.btnLED1_Clicked);
		this.btnLED2.Clicked += new global::System.EventHandler (this.btnLED2_Clicked);
	}
}
